name: met-ml
channels:
- conda-forge
- defaults
dependencies:
- bokeh=1.3
- bottleneck
- cartopy
- cupy
- dask-jobqueue
- dask-ml
- dask-mpi
- dask>=2.5.2
- datashader
- distributed>=2.5
- geopandas
- geoviews
- grpcio
- h5netcdf
- holoviews
- hvplot
- intake
- intake-xarray
- ipywidgets
- jupyter-server-proxy=1.1
- jupyter_contrib_nbextensions
- jupyterlab=1
- matplotlib
- metsim
- netcdf4
- nodejs
- numba
- numcodecs
- numpy
- pandas
- pip
- psutil
- pydap
- pyinterp
- pytest
- pytorch-gpu
- python-blosc
- python-graphviz
- python-wget
- rasterio
- scikit-learn
- scipy
- seaborn
- snakeviz
- sparse
- statsmodels
- tensorflow-gpu
- toolz
- tornado=6
- tqdm
- vega
- vega_datasets
- watermark
- xarray
- xesmf
- xlrd
- zarr
